/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Chris' at '28.06.16 12:55' with Gradle 2.9
 *
 * @author Chris, @date 28.06.16 12:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
