/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Chris' at '27.06.16 21:32' with Gradle 2.9
 *
 * @author Chris, @date 27.06.16 21:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
